<a href="https://colab.research.google.com/github/pierrebomfim/python-exercises/blob/master/Material_de_Estudo_aula1_e_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Foco no Mercado de Trabalho - aula 1

In [ ]:
# Material de Estudo U1S1 - Equação de segundo grau
a = 2
b = 0.5
c = 1
x = int(input("Digite o valor de x: "))

y = a * x ** 2 + b * x + c

print(f"O resultado de y para x = {x} é {y}.")

In [ ]:
# Material de Estudos U1s2 - Cálculo de IR

salario = 0
salario = float(input("Digite o salário do colaborador: "))

if salario <= 1903.98:
  print("Colaborador isento de IR")
elif salario <= 2826.65:
  print("O valor de IR será R$ 142.80")
  print(f"O salário líquido será de R$ {salario - 142.80}.")
elif salario <= 3751.05:
  print("O valor de IR será de R$ 354.80.")
  print(f"O salário líquido será de R$ {salario - 354.80}")
elif salario <= 4664.68:
  print("O valor de IR será de R$ 636.13")
  print(f"O salário líquido será de R$ {salario - 636.13}.")
else:
  print("O IR será de R$ 869.36")
  print(f"O salário líquido será de {salario - 869.36}")

In [ ]:
# Material de Estudos U1s3 - Cálculo do total de vendas de um produto

def calcular_valor(valor_prod, qtde, moeda='real', desconto=None, acrescimo=None):
  v_bruto = valor_prod * qtde

  if desconto:
    v_liquido = v_bruto - ( v_bruto * (desconto/100))
  elif acrescimo:
    v_liquido = v_bruto + ( v_bruto * (acrescimo/100))
  else:
    v_liquido = v_bruto

  if moeda == 'real':
    return v_liquido
  elif moeda =='dolar':
    return v_liquido * 5
  elif moeda == 'euro':
    return v_liquido * 5.7
  else:
    print('Moeda não cadastrada!')
    return 0

valor_a_pagar = calcular_valor(valor_prod=32, qtde=5, moeda='real', desconto=5)
print(f'O valor final da conta é {valor_a_pagar}.')


O valor final da conta é 152.0.



# **Aula 02 - u2s1** - Estruturas de Dados em Python

In [ ]:
#Sequência de caracteres

texto = 'Aprendendo Python na disciplina de Linguagem de Programação.'

print(f'A frase possui {len(texto)} caracteres.')
print(f"A palavra Python está em texto: {'Python' in texto}")
print(f"Qtde de vezes que o caracter y aparece no texto: {texto.count('y')}")
print(f'As 5 primeiras letras do texto são {texto[0:6]}')
print()

#alterando string

print(texto.upper())
print(texto.replace('a', 'xx'))
print()

#cortando a frase com split

palavras = texto.split()
print(f'As palavras do texto são: {palavras}')
print()

# Exemplo

texto_1 = """Operadores de String
Python oferece operadores para processar texto (ou seja, valores de string).
Assim como os números, as strings podem ser comparadas usando operadores de comparação:
==, !=, <, > e assim por diante.
O operador ==, por exemplo, retorna True se as strings nos dois lados do operador tiverem o mesmo valor (Perkovic, p. 23, 2016).
"""

print(f'Tamanho do texto: {len(texto_1)}')

texto_1 = texto_1.lower()

texto_1 = texto_1.replace(',', "").replace('.', "").replace('(', "").replace(')', "").replace('/n', "")

lista_de_palavras = texto_1.split()
print(f'Lista de palavras: {lista_de_palavras}')

string_strings = lista_de_palavras.count('string') + lista_de_palavras.count('strings')
print(f'Qtde de vezes que string/strings aparecem: {string_strings}')




A frase possui 60 caracteres.
A palavra Python está em texto: True
Qtde de vezes que o caracter y aparece no texto: 1
As 5 primeiras letras do texto são Aprend

APRENDENDO PYTHON NA DISCIPLINA DE LINGUAGEM DE PROGRAMAÇÃO.
Aprendendo Python nxx disciplinxx de Linguxxgem de Progrxxmxxção.

As palavras do texto são: ['Aprendendo', 'Python', 'na', 'disciplina', 'de', 'Linguagem', 'de', 'Programação.']

Tamanho do texto: 348
Lista de palavras: ['operadores', 'de', 'string', 'python', 'oferece', 'operadores', 'para', 'processar', 'texto', 'ou', 'seja', 'valores', 'de', 'string', 'assim', 'como', 'os', 'números', 'as', 'strings', 'podem', 'ser', 'comparadas', 'usando', 'operadores', 'de', 'comparação:', '==', '!=', '<', '>', 'e', 'assim', 'por', 'diante', 'o', 'operador', '==', 'por', 'exemplo', 'retorna', 'true', 'se', 'as', 'strings', 'nos', 'dois', 'lados', 'do', 'operador', 'tiverem', 'o', 'mesmo', 'valor', 'perkovic', 'p', '23', '2016']
Qtde de vezes que string/strings aparecem: 4


## Listas






In [ ]:
vogais = ['a', 'e', 'i', 'o', 'u']

for x in vogais:
    print(f'Posição = {vogais.index(x)}  Valor = {x}')

Posição = 0  Valor = a
Posição = 1  Valor = e
Posição = 2  Valor = i
Posição = 3  Valor = o
Posição = 4  Valor = u


In [ ]:
vogais = []

print(f'Tipo do objeto vogais: {type(vogais)}')
# append adiciona valor ao final da lista
vogais.append('a')
vogais.append('e')
vogais.append('i')
vogais.append('o')
vogais.append('u')

for p, v in enumerate(vogais):   #uso do enumerate
  print(f'Posição = {p}  Valor = {v}')


Tipo do objeto vogais: <class 'list'>
Posição = 0  Valor = a
Posição = 1  Valor = e
Posição = 2  Valor = i
Posição = 3  Valor = o
Posição = 4  Valor = u


In [ ]:
# Slice

lista = ['Python', 30.15, "Java", 51, ['a', 'b', 20], 'maça'] #lista com diferentes tipos de dados

print(f'Tamanho da Lista: {len(lista)}\n')

for p, i in enumerate(lista):
  print(f'Posição = {p}\t Valor = {i}\t ---------> tipo individual = {type(i)}')

print('\nExemplos de Slice\n')

print("lista[1] = ", lista[1])
print("lista[0:2] = ", lista[0:2])
print("lista[:2] = ", lista[:2])
print("lista[3:5] = ", lista[3:5])
print("lista[3:6] = ", lista[3:6])
print("lista[3:] = ", lista[3:])
print("lista[-2] = ", lista[-2])
print("lista[-1] = ", lista[-1])
print("lista[4][1] = ", lista[4][1])



Tamanho da Lista: 6

Posição = 0	 Valor = Python	 ---------> tipo individual = <class 'str'>
Posição = 1	 Valor = 30.15	 ---------> tipo individual = <class 'float'>
Posição = 2	 Valor = Java	 ---------> tipo individual = <class 'str'>
Posição = 3	 Valor = 51	 ---------> tipo individual = <class 'int'>
Posição = 4	 Valor = ['a', 'b', 20]	 ---------> tipo individual = <class 'list'>
Posição = 5	 Valor = maça	 ---------> tipo individual = <class 'str'>

Exemplos de Slice

lista[1] =  30.15
lista[0:2] =  ['Python', 30.15]
lista[:2] =  ['Python', 30.15]
lista[3:5] =  [51, ['a', 'b', 20]]
lista[3:6] =  [51, ['a', 'b', 20], 'maça']
lista[3:] =  [51, ['a', 'b', 20], 'maça']
lista[-2] =  ['a', 'b', 20]
lista[-1] =  maça
lista[4][1] =  b


In [ ]:
## List comprehension - listcomp

linguagens = ['Python', 'Java', 'Javascript', "C"]
print(f'Antes da listcomp: {linguagens}')

linguagens = [item.lower() for item in linguagens]
print(f'Após a listcomp: {linguagens}')

#Outra aplicação

linguagens = '''Python Java Javascript C '''.split()
linguagem_java = [item for item in linguagens if 'Java' in item]
print('\nNova Lista criada a partir da primeira, com os itens q tem o nome Java:')
print(linguagem_java)


Antes da listcomp: ['Python', 'Java', 'Javascript', 'C']
Após a listcomp: ['python', 'java', 'javascript', 'c']

Nova Lista criada a partir da primeira, com os itens q tem o nome Java:
['Java', 'Javascript']


In [ ]:
#Funções map(), list() e filter()

#Exemplo 1
print('Exemplo 1')
linguagens = '''Python Java Javascript C'''.split()

nova_lista = map(lambda x: x.lower(), linguagens)
print(f'A nova lista é: {nova_lista}\n')

nova_lista = list(nova_lista)
print(f'Agora sim, a nova lista é: {nova_lista}')

#Exemplo 2
print('\n\nExemplo 2')
numeros = [0, 1, 2, 3, 4, 5]

quadrados = list(map(lambda x: x*x, numeros))
print(f'Lista do número elevado a ele mesmo: {quadrados}')

#Exemplo 3 - filter
print('\n\nExemplo 3')
numeros = list(range(0,21))
print(f'Números de 0 à 20: {numeros}')

numeros_pares = list(filter(lambda x: x % 2 == 0, numeros))
print(f'Números pares: {numeros_pares}')

Exemplo 1
A nova lista é: <map object at 0x7fb0f07c0f98>

Agora sim, a nova lista é: ['python', 'java', 'javascript', 'c']


Exemplo 2
Lista do número elevado a ele mesmo: [0, 1, 4, 9, 16, 25]


Exemplo 3
Números de 0 à 20: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Números pares: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


## Tulpas

In [ ]:
vogais = ('a', 'e', 'i', 'o', 'u')
print(f'Tipo do objeto vogais: {type(vogais)}')

for p, x in enumerate(vogais):
  print(f'Posição = {p}\t Valor = {x}')
print()
for item in enumerate(vogais):
  print(item)
print()
print(tuple(enumerate(vogais)))
print(list(enumerate(vogais)))

Tipo do objeto vogais: <class 'tuple'>
Posição = 0	 Valor = a
Posição = 1	 Valor = e
Posição = 2	 Valor = i
Posição = 3	 Valor = o
Posição = 4	 Valor = u

(0, 'a')
(1, 'e')
(2, 'i')
(3, 'o')
(4, 'u')

((0, 'a'), (1, 'e'), (2, 'i'), (3, 'o'), (4, 'u'))
[(0, 'a'), (1, 'e'), (2, 'i'), (3, 'o'), (4, 'u')]


## Tipo *SET*

In [ ]:
vogais_1 = {'aeiou'} #sem uso do construtor
print(type(vogais_1), vogais_1)

vogais_2 = set('aeiouaaaa')  #construtor com string
print(type(vogais_2), vogais_2)

vogais_3 = set(['a', 'e', 'i', 'o', 'u']) #construtor com lista
print(type(vogais_3), vogais_3)

vogais_4 = set(('a', 'e', 'i', 'o', 'u')) # contrutor com tupla
print(type(vogais_4), vogais_4)

print(set('banana'))

<class 'set'> {'aeiou'}
<class 'set'> {'e', 'o', 'i', 'a', 'u'}
<class 'set'> {'e', 'o', 'i', 'a', 'u'}
<class 'set'> {'e', 'o', 'i', 'a', 'u'}
{'n', 'b', 'a'}


In [ ]:
# Exemplo - uma loja de informática recebeu componentes usados de um computador para avaliar se estão com defeito. As peças que não estiverem com defeito podem ser colocadas à venda.

def create_report():

  componentes_verificados = set(['caixas de som', 'cooler', 'dissipador de calor', 'cpu', 'hd', 'estabilizador', 'gabinete', 'hub', 'impressora', 'joystick', 'memória ram', 'microfone', 'modem', 'monitor', 'mouse', 'no-break', 'placa de captura', 'placa de som', 'placa de vídeo', 'placa mãe', 'scanner', 'teclado', 'webcam'])
  componentes_defeituosos = set(['hd', 'monitor', 'placa de som', 'scanner'])

  componentes_ok = componentes_verificados.difference(componentes_defeituosos)

  print(f'Foram verificados {len(componentes_verificados)} componentes, \n dos quais {len(componentes_defeituosos)} estão defeituosos.\n')

  print('Os componentes que podem ser vendidos são:')
  for item in componentes_ok:
    print(item)


create_report()




Foram verificados 23 componentes, 
 dos quais 4 estão defeituosos.

Os componentes que podem ser vendidos são:
webcam
dissipador de calor
placa de captura
microfone
memória ram
estabilizador
mouse
modem
impressora
hub
placa mãe
no-break
cooler
cpu
placa de vídeo
joystick
teclado
caixas de som
gabinete


## Tipo *MAPPING*

In [ ]:
# Exemplo 1 - Criação de dicionário vazio, com atribuição posterior de chave e valor

dici_1 = {}
dici_1['nome'] = 'João'
dici_1['idade'] = 30

# Exemplo 2 - Criação de dicionário usando um par de elementos na forma, chave : valor

dici_2 = {'nome': 'João', 'idade': 30}

# Exemplo 3 - Criação de dicionário com uma lista de tuplas. Cada tupla representa um par chave : valor

dici_3 = dict([('nome', 'João'), ('idade', 30)])

# Exemplo 4 - Criação de dicionário com a função built-in zip() e duas listas, uma com as chaves, outra com os valores.

dici_4 = dict(zip(['nome', 'idade'], ['João', 30]))

print(dici_1 == dici_2 == dici_3 == dici_4) # Testando se as diferentes construções resultamo em objetos iguais.

True


In [ ]:
cadastro = {
            'nome' : ['João', 'Ana', 'Pedro', 'Marcela'],
            'cidade' : ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba'],
            'idade' : [25, 33, 37, 18]
            }
print("len(cadastro) = ", len(cadastro))

print("\n cadastro.keys() =  \n", cadastro.keys())
print("\n cadastro.values() = \n", cadastro.values())
print("\n cadastro.items() = \n", cadastro.items())

print("\n cadastro['nome'] = ", cadastro['nome'])
print("\n cadastro['nome'][2] = ", cadastro['nome'][2])
print("\n cadastro['idade'][2:] = ", cadastro['idade'][2:])













len(cadastro) =  3

 cadastro.keys() =  
 dict_keys(['nome', 'cidade', 'idade'])

 cadastro.values() = 
 dict_values([['João', 'Ana', 'Pedro', 'Marcela'], ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba'], [25, 33, 37, 18]])

 cadastro.items() = 
 dict_items([('nome', ['João', 'Ana', 'Pedro', 'Marcela']), ('cidade', ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba']), ('idade', [25, 33, 37, 18])])

 cadastro['nome'] =  ['João', 'Ana', 'Pedro', 'Marcela']

 cadastro['nome'][2] =  Pedro

 cadastro['idade'][2:] =  [37, 18]


## Tipo ARRAY NUMPY

In [ ]:
import numpy

m1 = numpy.zeros((3, 3)) # Cria matriz 3 x 3 somente com zero
m2 = numpy.ones((2,2)) # Cria matriz 2 x 2 somente com um
m3 = numpy.eye(4) # Cria matriz 4 x 4 identidade
m4 = numpy.random.randint(low=0, high=100, size=10).reshape(2, 5) # Cria matriz 2 X 5 com números inteiros

print('\n numpy.zeros((3, 3)) = \n', numpy.zeros((3, 3)))
print('\n numpy.ones((2,2)) = \n', numpy.ones((2,2)))
print('\n numpy.eye(4) = \n', numpy.eye(4))
print('\n m4 = \n', m4)

print(f"Soma dos valores em m4 = {m4.sum()}")
print(f"Valor mínimo em m4 = {m4.min()}")
print(f"Valor máximo em m4 = {m4.max()}")
print(f"Média dos valores em m4 = {m4.mean()}")


 numpy.zeros((3, 3)) = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 numpy.ones((2,2)) = 
 [[1. 1.]
 [1. 1.]]

 numpy.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 m4 = 
 [[53 14  1 41 45]
 [ 8 27 14  7 94]]
Soma dos valores em m4 = 304
Valor mínimo em m4 = 1
Valor máximo em m4 = 94
Média dos valores em m4 = 30.4


## u2s2 - Mercado de Trabalho

*** Extrair uma lista com os dados das pessoas que ainda não receberam o email...

dados_1 = {
  'nome': ['Sonia Weber', 'Daryl Lowe', 'Vernon Carroll', 'Basil Gilliam', 'Mechelle Cobb', 'Edan Booker', 'Igor Wyatt', 'Ethan Franklin', 'Reed Williamson', 'Price Singleton'],
  'email': ['Lorem.ipsum@cursusvestibulumMauris.com', 'auctor@magnis.org', 'at@magnaUttincidunt.org', 'mauris.sagittis@sem.com', 'nec.euismod.in@mattis.co.uk', 'egestas@massaMaurisvestibulum.edu', 'semper.auctor.Mauris@Crasdolordolor.edu', 'risus.Quisque@condimentum.com', 'Donec@nislMaecenasmalesuada.net', 'Aenean.gravida@atrisus.edu'],
  'enviado': [False, False, False, False, False, False, False, True, False, False]
}

  dados_2 = {
  'nome': ['Travis Shepherd', 'Hoyt Glass', 'Jennifer Aguirre', 'Cassady Ayers', 'Colin Myers', 'Herrod Curtis', 'Cecilia Park', 'Hop Byrd', 'Beatrice Silva', 'Alden Morales'],
  'email': ['at@sed.org', 'ac.arcu.Nunc@auctor.edu', 'nunc.Quisque.ornare@nibhAliquam.co.uk', 'non.arcu@mauriseu.com', 'fringilla.cursus.purus@erategetipsum.ca', 'Fusce.fermentum@tellus.co.uk', 'dolor.tempus.non@ipsum.net', 'blandit.congue.In@libero.com', 'nec.tempus.mauris@Suspendisse.com', 'felis@urnaconvalliserat.org'],
  'enviado': [False, False, False, True, True, True, False, True, True, False]
}

In [ ]:
def extrair_lista_email(dict_1, dict_2):
  
  list_1 = list(zip(dict_1['nome'], dict_1['email'], dict_1['enviado']))
  print(f'Amostra da lista 1: {list_1[0]}\n')

  list_2 = list(zip(dict_2['nome'], dict_2['email'], dict_2['enviado']))

  dados = list_1 + list_2
  print(f'Amostra dos dados: {dados[:2]}\n\n')

  emails = [item[1] for item in dados if not item[2]]

  return emails



dados_1 = { 'nome': ['Sonia Weber', 'Daryl Lowe', 'Vernon Carroll', 'Basil Gilliam', 'Mechelle Cobb', 'Edan Booker', 'Igor Wyatt', 'Ethan Franklin', 'Reed Williamson', 'Price Singleton'],
           'email': ['Lorem.ipsum@cursusvestibulumMauris.com', 'auctor@magnis.org', 'at@magnaUttincidunt.org', 'mauris.sagittis@sem.com', 'nec.euismod.in@mattis.co.uk', 'egestas@massaMaurisvestibulum.edu', 'semper.auctor.Mauris@Crasdolordolor.edu', 'risus.Quisque@condimentum.com', 'Donec@nislMaecenasmalesuada.net', 'Aenean.gravida@atrisus.edu'],
           'enviado': [False, False, False, False, False, False, False, True, False, False] }

dados_2 = { 'nome': ['Travis Shepherd', 'Hoyt Glass', 'Jennifer Aguirre', 'Cassady Ayers', 'Colin Myers', 'Herrod Curtis', 'Cecilia Park', 'Hop Byrd', 'Beatrice Silva', 'Alden Morales'], 
           'email': ['at@sed.org', 'ac.arcu.Nunc@auctor.edu', 'nunc.Quisque.ornare@nibhAliquam.co.uk', 'non.arcu@mauriseu.com', 'fringilla.cursus.purus@erategetipsum.ca', 'Fusce.fermentum@tellus.co.uk', 'dolor.tempus.non@ipsum.net', 'blandit.congue.In@libero.com', 'nec.tempus.mauris@Suspendisse.com', 'felis@urnaconvalliserat.org'],
           'enviado': [False, False, False, True, True, True, False, True, True, False] }

emails = extrair_lista_email(dict_1=dados_1, dict_2=dados_2)
print(f'Emails a serem enviados:\n {emails}')


Amostra da lista 1: ('Sonia Weber', 'Lorem.ipsum@cursusvestibulumMauris.com', False)

Amostra dos dados: [('Sonia Weber', 'Lorem.ipsum@cursusvestibulumMauris.com', False), ('Daryl Lowe', 'auctor@magnis.org', False)]


Emails a serem enviados:
 ['Lorem.ipsum@cursusvestibulumMauris.com', 'auctor@magnis.org', 'at@magnaUttincidunt.org', 'mauris.sagittis@sem.com', 'nec.euismod.in@mattis.co.uk', 'egestas@massaMaurisvestibulum.edu', 'semper.auctor.Mauris@Crasdolordolor.edu', 'Donec@nislMaecenasmalesuada.net', 'Aenean.gravida@atrisus.edu', 'at@sed.org', 'ac.arcu.Nunc@auctor.edu', 'nunc.Quisque.ornare@nibhAliquam.co.uk', 'dolor.tempus.non@ipsum.net', 'felis@urnaconvalliserat.org']


# **Aula 02 - u2s2** - Algoritimos de Busca

In [ ]:
# Algoritimos de Busca

nomes = 'João Paulo André Tiago'.split()

print('Paulo' in nomes)
print('Paulo' not in nomes)

True
False


In [ ]:
# Busca Linear - Usando o index()

vogais = 'aeiou'
resultado = vogais.index('a')
print(f"O index é: {resultado_1} ")

# Se o valor procurado não for encontrado, retornará um erro (valueerror)

O index é: 4 


In [ ]:
# Busca Linear - Busca de index com algoritimo próprio

def buscar_index(lista, valor):
  tamanho_lista = len(lista)
  for i in range(tamanho_lista):
    if valor == lista[i]:
      return i
  return None 


vogais = 'aeiou'
vogal = input(f'Digite o valor que deseja encontar:')

resultado = buscar_index(lista=vogais, valor=vogal)

if resultado != None:
  print(f'O idex é {resultado}')
else:
  print('O valor não foi encontrado')



Digite o valor que deseja encontar:b
O valor não foi encontrado


In [ ]:
# Busca Binária

def executar_busca_binaria(lista, valor):
  minimo = 0
  maximo = len(lista) - 1

  while minimo <= maximo:
    meio = (maximo + minimo) //2
    
    if valor < lista[meio]:
      maximo = meio - 1
    elif valor > lista[meio]:
      minimo = meio + 1
    else:
      return True
  return False

lista = list(range(0, 50))
print(lista)

print('\n', executar_busca_binaria(lista=lista, valor=10))
print('\n', executar_busca_binaria(lista=lista, valor=100))



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

 True

 False


In [ ]:
# Busca Binária - Encontrar o valor e seu index

def buscar_valor(lista, valor):
  minimo = 0
  maximo = len(lista) - 1

  while minimo <= maximo:
    meio = (minimo + maximo) // 2
    if valor < lista[meio]:
      maximo = meio - 1
    elif valor > lista[meio]:
      minimo = meio + 1
    else:
      return meio
  return None

lista = list(range(1, 10))

resultado = buscar_valor(lista=lista, valor=5)
if resultado:
  print(f'\nValor encontrado na posição {resultado}')
else:
  print('\nValor não encontrado!')


Valor encontrado na posição 4


**Aula 02 - u2s2** - Mercado de Trabalho

In [33]:
# Dedup #

# Parte 1 - Implementar algoritimo de Busca Linear

def executar_busca_linear(lista, valor):
  tamanho_lista = len(lista)
  for i in range(tamanho_lista):
    if valor == lista[i]:
      return True
  return False

# Parte 2 - Criação da lista Dedup e tratamento dos cpf's

def criar_lista_dedup(lista):
  lista_dedup = []
  for cpf in lista:
    cpf = str(cpf)
    cpf = cpf.replace('.', "").replace('-', "")
    if len(cpf) == 11:
      if not executar_busca_linear(lista_dedup, cpf):
        lista_dedup.append(cpf)
  return lista_dedup

# Implementação de teste

def testar_funcao(lista_cpf):
  lista_dedup = criar_lista_dedup(lista_cpf)
  print(lista_dedup)

lista_cpf = ['111.111.111-11', '11111111111', '222.222.222-22', '333.333.333-33', '22222222222', '444.44444']
testar_funcao(lista_cpf)




['11111111111', '22222222222', '33333333333']


# **Aula 02 - u2s3** - Algoritimos de Ordenação

**Aula 02 - u2s3** - Mercado de Trabalho